### ISSUE TITLE
CRC with Array Field

### ISSUE THREAD

**Issue by crunchy234** [ZiglioUK/construct#7]
Hi just wondering how to use a `CRC` with `Array` in the inner struct.

I have the following code:
```.java
    private static CRCFunc CRC16 = new CRCFunc() {
        public boolean check(byte[] bytes, int crc_val) {
            int cs = compute(bytes);
            return crc_val == cs;
        }

        @Override
        public int compute(byte[] bytes) {
            int cs = (int) calculateChecksum(bytes);
            return cs;
        }
    };

    private static Construct struct =
            CRC(Struct(null,
                    ULInt16("packet_type"),
                    ULInt16("payload_size"),
                    Array(ctx -> ctx.get("payload_size"), ULInt8("packet_data"))
                    ),
                    ULInt16("checksum"),
                    CRC16
            );

```
and when I run:
```.kt
        Container inputStruct = struct.parse(hexStringToByteArray("000002000600299A"));
```
I get the following exception:
```
com.sirtrack.construct.Core$SizeofError
	at com.sirtrack.construct.Core$Construct.sizeof(Core.java:359)
	at com.sirtrack.construct.Macros$CRC._sizeof(Macros.java:638)
	at com.sirtrack.construct.Macros$CRC._parse(Macros.java:571)
	at com.sirtrack.construct.Core$Construct.parse_stream(Core.java:312)
	at com.sirtrack.construct.Core$Construct.parse(Core.java:299)
```
Which I can see is caused by `ctx -> ctx.get("payload_size")` being called while `ctx` has a dict of size 1 with key `_` and value `{}`.

P.S. I'm new to using construct. Also using version 1.1.2

**Comment by crunchy234** [comment]
https://github.com/crunchy234/construct/tree/feat/crc-arrays
I have got the decode fixed and added a test case.
Still unsure how to get the encode test case working.
It is failing in `_buildCrcField` because the `_sizeof` method does not get the context that is built up in `subcon._build` and when it gets to the array length calculation (`ctx -> ctx.get("payload_size")`) `cxt` only contains `{}`.

Would be grateful for any pointers on how I fix the encode test and/or if I have somehow broken/missed  something in the decode fixes.

**Comment by ZiglioUK** [comment]
Good catch. There are always problems with _sizeof. Especially with dynamic constructs whose size depends on some other values. That requires some adhoc solutions usually
